cart/urls.py
from django.urls import path
from .views import cart_add_product, cart_detail, cart_remove_product

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add_product, name='cart_add_product'),
    path('remove/<int:product_id>/', cart_remove_product, name='cart_remove_product'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i))
    for i in range(1, 21)
]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add_product(request, product_id):
    """
    Добавление Товара в Корзину
    :param request:
    :param product_id:
    :return:
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove_product(request, product_id):
    """
    Удаление товара из корзины
    :return:
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """
    Отображает страницу с Товарами, добавленными в Корзину
    :param request:
    :return:
    """
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={'quantity': item['quantity'],
                                                 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Ваша корзина{% endblock %}

{% block content %}
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена</th>
            <th>Стоимость</th>
        </tr>
        </thead>
        <tbody>

        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}
                                      {% else %}{% static "img/no_image.png" %}
                                      {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url "cart:cart_add_product" product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a href="{% url "cart:cart_remove_product" product.id %}">Удалить</a></td>
                    <td class="num">{{ item.price }} руб.</td>
                    <td class="num">{{ item.total_price }} руб.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Продолжить покупки</a>
        <a href="{% url "orders:order_create" %}" class="button">Оформить заказ</a>
    </p>
{% endblock %}